### PR TITLE
remove type index mentions

### PR DESCRIPTION
**Pull request by jeff-zucker**

### CODE REVIEW

**Review by elf-pavlik — APPROVED** [review]
👍

**Comment by elf-pavlik** [comment]
I just noticed that this PR doesn't update the diagram: https://github.com/solid/webid-profile/blob/main/profile-discovery.png

**Comment by jeff-zucker** [comment]
Yes, thanks, I'm waiting on a bit of clarity from #40 before redoing the diagram  to remove the type indexes.

**Comment by csarven** [comment]
Follows ACTION of https://github.com/solid/webid-profile/blob/main/meetings/2022-08-23.md#separation-of-index-content : https://github.com/solid/webid-profile/pull/43 and https://github.com/solid/webid-profile/issues/35 .

**Pull request merged**
