### PR TITLE
Remove storage section, update data model

### PR DESCRIPTION
**Pull request by VirginiaBalseiro**

### CODE REVIEW

**Review by csarven — APPROVED** [review]

**Comment by csarven** [comment]
Not sure if there is a way but I can't make a change suggestion that goes beyond the lines changed in this PR - was going to say it should be similar to #webid-profile-data-model and #preferences-document like:

* Zero or more <code>pim:storage</code> properties to indicate agent's storages.

**Comment by VirginiaBalseiro** [comment]
> Not sure if there is a way but I can't make a change suggestion that goes beyond the lines changed in this PR - was going to say it should be similar to #webid-profile-data-model and #preferences-document like:
> 
> * Zero or more `pim:storage` properties to indicate agent's storages.

I am not sure I understand your suggestion. Are you saying the line changed in this PR should be replaced with the bullet point you suggest?

**Comment by csarven** [comment]
That works better yes but then the Storage section should be removed or described in other ways. As it stands, there is nothing particularly useful - it is redundant given the webid profile data model.

**Comment by VirginiaBalseiro** [comment]
> That works better yes but then the Storage section should be removed or described in other ways. As it stands, there is nothing particularly useful - it is redundant given the webid profile data model.

I agree. I'll close this PR and open another one to remove the section.

**Review by csarven — APPROVED** [review]

**Pull request merged**
